name: CI

on:
  push:
    branches:
      - main
      - bananas
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: ['20.11.0', '22.9.0']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
      - name: Setup Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: ${{ matrix.version }}
      - name: Install Dependencies
        run: npm ci
      - name: Save error log
        uses: actions/upload-artifact@v4.4.0
        if: ${{ failure() }}
        with:
          name: npm-debug-log-${{ hashFiles('package-lock.json') }}
          path: npm-debug.log
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Report Coverage
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Pack
        run: npm pack
